# Generated by Django 4.1.2 on 2022-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=100, null=True)),
                ('employee_email', models.EmailField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('employee_sex', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'other')], default='OTHER', max_length=50, null=True)),
            ],
        ),
    ]
