# Generated by Django 4.1.3 on 2022-11-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('cinema_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cinema_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concession_stand',
            fields=[
                ('station_number', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.CharField(blank=True, max_length=250, null=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=50, null=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Show_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.movie')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_sex',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'other')], default='OTHER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Transaction_receipt',
            fields=[
                ('transaction_number', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', null=True)),
                ('row_letter', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2, null=True)),
                ('classification', models.BooleanField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, choices=[(10.0, 'Adult Ticket $10.00'), (5.0, 'Kid Ticket $5.00')], default='0.00', null=True)),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('show_time_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.show_time')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('items_ordered', models.CharField(blank=True, max_length=250, null=True)),
                ('pick_up_time', models.IntegerField(blank=True, null=True)),
                ('concession_stand_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.concession_stand')),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
    ]
